# fly.toml app configuration file generated for nestjs-spells-api on 2023-08-28T11:28:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nestjs-spells-api"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
